GET http://localhost:3000/Users

### get 1 user
GET http://localhost:3000/Users/20

### phan trang
GET http://localhost:3000/Users?trang=1&soLuong=5

### create user
POST http://localhost:3000/Users
Content-Type: application/json

{
  "ten": "Nguyễn Văn A",
  "email": "vana@example2.com",
  "tendangnhap": "vana1236",
  "matkhau": "123456",
  "nhaclaimatkhau": "123456"
}

### PATCH
PATCH http://localhost:3000/Users/3
Content-Type: application/json

{
    "ten": "Nguyễn Văn A",
    "matkhau": "123456",
    "nhaclaimatkhau": "123456"
}

### DELETE
DELETE http://localhost:3000/Users/22

####

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "tendangnhap": "nguyenvana",
  "matkhau": "123456"
}

###
GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NzQ0MzE3NjEsImV4cCI6MTc3NDUxODE2MX0.oSH7V9udwNaDbiuFhEsFAhin4Ze0kpoaXpxO3r-JNsU